const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Soumi Guria";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const alreadyHaveAccount = "Already have an account? ";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const home = "Home", categories = "Categories", cart = "Cart", account = "Account";
const searchanything = "Search anything...", todayDeal = "Today's Deal", flashsale = "Flash Sale", topSellers = "Top Sellers", brand = "Brand", topCategories = "Top Categories", featureCategories = "Featured Categories";